# Prometheus/prometheus.yml
global:
  scrape_interval: 20s
  evaluation_interval: 20s

scrape_configs:
  # Prometheus self-monitoring
  - job_name: "prometheus"
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ["localhost:9090"]
  
  # Survival prediction app
  - job_name: "survival_prediction"
    metrics_path: '/metrics'
    scrape_interval: 15s
    static_configs:
      - targets: ["survival_prediction:8000"]  # Use service name for internal Docker networking